### ISSUE TITLE
Moving a Houdini Actor between levels destroys it

### ISSUE THREAD

**Issue by simco50** [sideeffects/HoudiniEngineForUnreal#121]
Hi,

When moving a Houdini Actor to another level, it deletes itself and work is lost.
It's 100% reproducible.
Is there any change I can make to fix this?

Thanks in advance,
Simon

**Comment by dpernuit** [comment]
Hi,

This is a well known issue in version 1, and is mainly due to how unreal handles cut and paste/move to level that doesn't work well with custom serialization based components.
It is fixed in version 2 of the plugin, but there is no trivial solution for this for v1.

The only workaround I can offer for v1 is to use copy paste.
(but not duplicate/alt + drag! as duplicate has its own set of issues in v1 as well)
