### ISSUE TITLE
Landscape sizes

### ISSUE THREAD

**Issue by alexgeek** [sideeffects/HoudiniEngineForUnreal#132]
Hi there,

I'm not fond of the behaviour that the plugin tries to guess the desired landscape size configuration. 

I'm in the process of adding two attributes 'unreal_landscape_sections_per_component' and 'unreal_landscape_quads_per_section' that will be used instead of guessing. 

I did notice on [this line](https://github.com/sideeffects/HoudiniEngineForUnreal/blob/c74768e6c4d98d5167091993438102626bc1451f/Source/HoudiniEngineRuntime/Private/HoudiniLandscapeUtils.cpp#L843) that the section sizes are listed as 7, 15, 31, 63, 127 and 255. Based on the [UE4 docs](https://docs.unrealengine.com/en-US/Engine/Landscape/TechnicalGuide/index.html) shouldn't that final value be 254 not 255?

Also would the change be welcomed in a pull request?

**Comment by dpernuit** [comment]
Hi,

Adding those two attributes is actually something I've considered for a while, but since nobody asked for it / complained about the current behavior, never actually added. PR are always welcome.

The sections size array is correct, as it is for the number of quads per sections, not the size in points of the sections themselves.
That code is actually coming straight up from UE, see FNewLandscapeUtils::ChooseBestComponentSizeForImport(...)

**Comment by alexgeek** [comment]
Oh yes it is right. I've implemented this but realised I just copied it from program files, will submit a pull request when I switch it over to use the git repository.

**Comment by alexgeek** [comment]
@dpernuit saw you closed the pull request 4 years later 😅.
Closing the ticket too.
