### ISSUE TITLE
why add this,// In partitioned world, we treat these actors as editor only

### ISSUE THREAD

**Issue by cgTD123** [sideeffects/HoudiniEngineForUnreal#189]
why add this ,if I pass it,what will be happened,and why a houdini asset actor with landscope still work in Game,confuse about this

**Comment by dpernuit** [comment]
Hi,

Thanks a lot for bringing this up! I was looking into that fixing the issue this caused, and your comment helped a lot!

This change was actually made by Epic when working on the Matrix Awakens demo.
Likely, it was made to prevent issues due to it being made with very early alpha versions of UE5/WorldPartition.

Those issues in the engine have been fixed in the release version of UE5, but that change remained, causing the cooked data from HDA to not appear in Game... (which was not intended at all!)

That'll be gone in tomorrow's build of the plugin.
