### ISSUE TITLE
Houdini Engine for Unreal Content Examples

### ISSUE THREAD

**Issue by KenosDromos** [sideeffects/HoudiniEngineForUnreal#294]
The Houdini Engine documentation has a topic called "Content examples overview", which shows examples of the use of many useful mechanisms. But the files in the SideFX repository have been deleted. Can you tell me if there are similar examples and whether support for such training materials will be resumed in the future?

**Comment by dpernuit** [comment]
Hi,
Sorry for the late reply! Those files weren't deleted - you just saw the docs page before the Content Examples were released!
They've been available since the last prod build, and are available [HERE](https://github.com/sideeffects/HoudiniEngineForUnreal-ContentExamples)

And with a recent version of the HE plugin, you now have links to the CE directly in the HE menu in Unreal.
