### ISSUE TITLE
Asset Input lost after reloading the .umap

### ISSUE THREAD

**Issue by kcmonkey** [sideeffects/HoudiniEngineForUnreal#74]
Hi,

I'm using a "operator path" as one of my digital asset parameter and it shows up correctly in engine's property window. And Then I change input type of operator path to "Asset Input" and choose another houdini digital asset as my input, everything works fine so far. But if I save and reload the current map, my input to another digital asset will lost even thou the asset name still shows in "Current Selection" section. Is there a serialization issue with hda actors?

Thanks.

**Comment by dpernuit** [comment]
Hi,

I just submitted a fix for this issue, it will be available in tomorrow's build of the plug-in (16.0.695). 

The main issue for this wasn't due to serialization, but to the fact that the connected asset wasn't cooked after loading the level, which in result broke the input connection.
Since it's not a serialization issue, you should be able to use those assets normally after loading the level once your plug-in is updated.
