### ISSUE TITLE
Tiled Heightmap Exports from Houdini have open seams when used with world composition

### ISSUE THREAD

**Issue by Skullfurious** [sideeffects/HoudiniEngineForUnreal#87]
When exporting a tiled heightmap from Houdini and importing into UE4 there are visible seams between the edges. Edges almost line up but are not fully accurate. The only solution for the time being is using the retopo tool but there is way too much terrain for the small max brush size UE4 has.

Unsure of what's causing the issue. The original size of the landscape is 2020m.

Example:
https://i.imgur.com/jvc4u0l.png
https://i.imgur.com/L0aOAMP.png

**Comment by dpernuit** [comment]
Hi,

This has been fixed in today's daily build (17.0.395).

The HF_Output node now has an additional parameter when exporting tiles, called “Tile Overlap”, it allows tiles to share a given amount of points on their border.

For game engines export (and specifically for unreal), you'll want to set the overlap to (1,1).
(also make sure that the tile size you export matches unreal's landscape size requirements).
